services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: taskmgtpw
        ports:
            - 4422:5432
        volumes:
            - db:/var/lib/postgresql/data  
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
    db: